/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DebugParkingRouteImport } from './routes/debug.parking'
import { Route as AdminValidationRouteImport } from './routes/admin.validation'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProviderSyncRouteImport } from './routes/admin.provider-sync'
import { Route as AdminLaCoverageRouteImport } from './routes/admin.la-coverage'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminForecastRouteImport } from './routes/admin.forecast'
import { Route as AdminBetaReadinessRouteImport } from './routes/admin.beta-readiness'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DebugParkingRoute = DebugParkingRouteImport.update({
  id: '/debug/parking',
  path: '/debug/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminValidationRoute = AdminValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProviderSyncRoute = AdminProviderSyncRouteImport.update({
  id: '/provider-sync',
  path: '/provider-sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaCoverageRoute = AdminLaCoverageRouteImport.update({
  id: '/la-coverage',
  path: '/la-coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForecastRoute = AdminForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBetaReadinessRoute = AdminBetaReadinessRouteImport.update({
  id: '/beta-readiness',
  path: '/beta-readiness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/session': typeof SessionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/beta-readiness': typeof AdminBetaReadinessRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/la-coverage': typeof AdminLaCoverageRoute
  '/admin/provider-sync': typeof AdminProviderSyncRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/validation': typeof AdminValidationRoute
  '/debug/parking': typeof DebugParkingRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/session': typeof SessionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/beta-readiness': typeof AdminBetaReadinessRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/la-coverage': typeof AdminLaCoverageRoute
  '/admin/provider-sync': typeof AdminProviderSyncRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/validation': typeof AdminValidationRoute
  '/debug/parking': typeof DebugParkingRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/session': typeof SessionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/beta-readiness': typeof AdminBetaReadinessRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/la-coverage': typeof AdminLaCoverageRoute
  '/admin/provider-sync': typeof AdminProviderSyncRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/validation': typeof AdminValidationRoute
  '/debug/parking': typeof DebugParkingRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/saved'
    | '/scan'
    | '/session'
    | '/admin/analytics'
    | '/admin/beta-readiness'
    | '/admin/forecast'
    | '/admin/health'
    | '/admin/la-coverage'
    | '/admin/provider-sync'
    | '/admin/reports'
    | '/admin/validation'
    | '/debug/parking'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/saved'
    | '/scan'
    | '/session'
    | '/admin/analytics'
    | '/admin/beta-readiness'
    | '/admin/forecast'
    | '/admin/health'
    | '/admin/la-coverage'
    | '/admin/provider-sync'
    | '/admin/reports'
    | '/admin/validation'
    | '/debug/parking'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/saved'
    | '/scan'
    | '/session'
    | '/admin/analytics'
    | '/admin/beta-readiness'
    | '/admin/forecast'
    | '/admin/health'
    | '/admin/la-coverage'
    | '/admin/provider-sync'
    | '/admin/reports'
    | '/admin/validation'
    | '/debug/parking'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ScanRoute: typeof ScanRoute
  SessionRoute: typeof SessionRoute
  DebugParkingRoute: typeof DebugParkingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/debug/parking': {
      id: '/debug/parking'
      path: '/debug/parking'
      fullPath: '/debug/parking'
      preLoaderRoute: typeof DebugParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/validation': {
      id: '/admin/validation'
      path: '/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AdminValidationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provider-sync': {
      id: '/admin/provider-sync'
      path: '/provider-sync'
      fullPath: '/admin/provider-sync'
      preLoaderRoute: typeof AdminProviderSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/la-coverage': {
      id: '/admin/la-coverage'
      path: '/la-coverage'
      fullPath: '/admin/la-coverage'
      preLoaderRoute: typeof AdminLaCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forecast': {
      id: '/admin/forecast'
      path: '/forecast'
      fullPath: '/admin/forecast'
      preLoaderRoute: typeof AdminForecastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beta-readiness': {
      id: '/admin/beta-readiness'
      path: '/beta-readiness'
      fullPath: '/admin/beta-readiness'
      preLoaderRoute: typeof AdminBetaReadinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBetaReadinessRoute: typeof AdminBetaReadinessRoute
  AdminForecastRoute: typeof AdminForecastRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLaCoverageRoute: typeof AdminLaCoverageRoute
  AdminProviderSyncRoute: typeof AdminProviderSyncRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminValidationRoute: typeof AdminValidationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBetaReadinessRoute: AdminBetaReadinessRoute,
  AdminForecastRoute: AdminForecastRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminLaCoverageRoute: AdminLaCoverageRoute,
  AdminProviderSyncRoute: AdminProviderSyncRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminValidationRoute: AdminValidationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ScanRoute: ScanRoute,
  SessionRoute: SessionRoute,
  DebugParkingRoute: DebugParkingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
