/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DebugParkingRouteImport } from './routes/debug.parking'
import { Route as AdminValidationRouteImport } from './routes/admin.validation'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProviderSyncRouteImport } from './routes/admin.provider-sync'
import { Route as AdminLaCoverageRouteImport } from './routes/admin.la-coverage'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminForecastRouteImport } from './routes/admin.forecast'
import { Route as AdminBetaReadinessRouteImport } from './routes/admin.beta-readiness'
import { Route as AdminBellevueCoverageRouteImport } from './routes/admin.bellevue-coverage'
import { Route as AdminArlingtonCoverageRouteImport } from './routes/admin.arlington-coverage'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAccuracyRouteImport } from './routes/admin.accuracy'
import { Route as ApiPublicCronSyncLaOccupancyRouteImport } from './routes/api/public/cron.sync-la-occupancy'
import { Route as ApiPublicCronHealthCheckRouteImport } from './routes/api/public/cron.health-check'
import { Route as ApiPublicAdminSyncLaRouteImport } from './routes/api/public/admin.sync-la'
import { Route as ApiPublicAdminSyncBellevueRouteImport } from './routes/api/public/admin.sync-bellevue'
import { Route as ApiPublicAdminSyncArlingtonRouteImport } from './routes/api/public/admin.sync-arlington'
import { Route as ApiPublicAdminRunScannerSelfTestRouteImport } from './routes/api/public/admin.run-scanner-self-test'
import { Route as ApiPublicAdminArlingtonSelfTestRouteImport } from './routes/api/public/admin.arlington-self-test'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DebugParkingRoute = DebugParkingRouteImport.update({
  id: '/debug/parking',
  path: '/debug/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminValidationRoute = AdminValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProviderSyncRoute = AdminProviderSyncRouteImport.update({
  id: '/provider-sync',
  path: '/provider-sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaCoverageRoute = AdminLaCoverageRouteImport.update({
  id: '/la-coverage',
  path: '/la-coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForecastRoute = AdminForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBetaReadinessRoute = AdminBetaReadinessRouteImport.update({
  id: '/beta-readiness',
  path: '/beta-readiness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBellevueCoverageRoute = AdminBellevueCoverageRouteImport.update({
  id: '/bellevue-coverage',
  path: '/bellevue-coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArlingtonCoverageRoute = AdminArlingtonCoverageRouteImport.update({
  id: '/arlington-coverage',
  path: '/arlington-coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccuracyRoute = AdminAccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronSyncLaOccupancyRoute =
  ApiPublicCronSyncLaOccupancyRouteImport.update({
    id: '/api/public/cron/sync-la-occupancy',
    path: '/api/public/cron/sync-la-occupancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHealthCheckRoute =
  ApiPublicCronHealthCheckRouteImport.update({
    id: '/api/public/cron/health-check',
    path: '/api/public/cron/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncLaRoute = ApiPublicAdminSyncLaRouteImport.update({
  id: '/api/public/admin/sync-la',
  path: '/api/public/admin/sync-la',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSyncBellevueRoute =
  ApiPublicAdminSyncBellevueRouteImport.update({
    id: '/api/public/admin/sync-bellevue',
    path: '/api/public/admin/sync-bellevue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncArlingtonRoute =
  ApiPublicAdminSyncArlingtonRouteImport.update({
    id: '/api/public/admin/sync-arlington',
    path: '/api/public/admin/sync-arlington',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminRunScannerSelfTestRoute =
  ApiPublicAdminRunScannerSelfTestRouteImport.update({
    id: '/api/public/admin/run-scanner-self-test',
    path: '/api/public/admin/run-scanner-self-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminArlingtonSelfTestRoute =
  ApiPublicAdminArlingtonSelfTestRouteImport.update({
    id: '/api/public/admin/arlington-self-test',
    path: '/api/public/admin/arlington-self-test',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/accuracy': typeof AdminAccuracyRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/arlington-coverage': typeof AdminArlingtonCoverageRoute
  '/admin/bellevue-coverage': typeof AdminBellevueCoverageRoute
  '/admin/beta-readiness': typeof AdminBetaReadinessRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/la-coverage': typeof AdminLaCoverageRoute
  '/admin/provider-sync': typeof AdminProviderSyncRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/validation': typeof AdminValidationRoute
  '/debug/parking': typeof DebugParkingRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/admin/arlington-self-test': typeof ApiPublicAdminArlingtonSelfTestRoute
  '/api/public/admin/run-scanner-self-test': typeof ApiPublicAdminRunScannerSelfTestRoute
  '/api/public/admin/sync-arlington': typeof ApiPublicAdminSyncArlingtonRoute
  '/api/public/admin/sync-bellevue': typeof ApiPublicAdminSyncBellevueRoute
  '/api/public/admin/sync-la': typeof ApiPublicAdminSyncLaRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/sync-la-occupancy': typeof ApiPublicCronSyncLaOccupancyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/accuracy': typeof AdminAccuracyRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/arlington-coverage': typeof AdminArlingtonCoverageRoute
  '/admin/bellevue-coverage': typeof AdminBellevueCoverageRoute
  '/admin/beta-readiness': typeof AdminBetaReadinessRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/la-coverage': typeof AdminLaCoverageRoute
  '/admin/provider-sync': typeof AdminProviderSyncRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/validation': typeof AdminValidationRoute
  '/debug/parking': typeof DebugParkingRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/admin/arlington-self-test': typeof ApiPublicAdminArlingtonSelfTestRoute
  '/api/public/admin/run-scanner-self-test': typeof ApiPublicAdminRunScannerSelfTestRoute
  '/api/public/admin/sync-arlington': typeof ApiPublicAdminSyncArlingtonRoute
  '/api/public/admin/sync-bellevue': typeof ApiPublicAdminSyncBellevueRoute
  '/api/public/admin/sync-la': typeof ApiPublicAdminSyncLaRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/sync-la-occupancy': typeof ApiPublicCronSyncLaOccupancyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/accuracy': typeof AdminAccuracyRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/arlington-coverage': typeof AdminArlingtonCoverageRoute
  '/admin/bellevue-coverage': typeof AdminBellevueCoverageRoute
  '/admin/beta-readiness': typeof AdminBetaReadinessRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/la-coverage': typeof AdminLaCoverageRoute
  '/admin/provider-sync': typeof AdminProviderSyncRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/validation': typeof AdminValidationRoute
  '/debug/parking': typeof DebugParkingRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/admin/arlington-self-test': typeof ApiPublicAdminArlingtonSelfTestRoute
  '/api/public/admin/run-scanner-self-test': typeof ApiPublicAdminRunScannerSelfTestRoute
  '/api/public/admin/sync-arlington': typeof ApiPublicAdminSyncArlingtonRoute
  '/api/public/admin/sync-bellevue': typeof ApiPublicAdminSyncBellevueRoute
  '/api/public/admin/sync-la': typeof ApiPublicAdminSyncLaRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/sync-la-occupancy': typeof ApiPublicCronSyncLaOccupancyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/onboard'
    | '/profile'
    | '/saved'
    | '/scan'
    | '/session'
    | '/settings'
    | '/splash'
    | '/subscription'
    | '/admin/accuracy'
    | '/admin/analytics'
    | '/admin/arlington-coverage'
    | '/admin/bellevue-coverage'
    | '/admin/beta-readiness'
    | '/admin/forecast'
    | '/admin/health'
    | '/admin/la-coverage'
    | '/admin/provider-sync'
    | '/admin/reports'
    | '/admin/validation'
    | '/debug/parking'
    | '/admin/'
    | '/api/public/admin/arlington-self-test'
    | '/api/public/admin/run-scanner-self-test'
    | '/api/public/admin/sync-arlington'
    | '/api/public/admin/sync-bellevue'
    | '/api/public/admin/sync-la'
    | '/api/public/cron/health-check'
    | '/api/public/cron/sync-la-occupancy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/onboard'
    | '/profile'
    | '/saved'
    | '/scan'
    | '/session'
    | '/settings'
    | '/splash'
    | '/subscription'
    | '/admin/accuracy'
    | '/admin/analytics'
    | '/admin/arlington-coverage'
    | '/admin/bellevue-coverage'
    | '/admin/beta-readiness'
    | '/admin/forecast'
    | '/admin/health'
    | '/admin/la-coverage'
    | '/admin/provider-sync'
    | '/admin/reports'
    | '/admin/validation'
    | '/debug/parking'
    | '/admin'
    | '/api/public/admin/arlington-self-test'
    | '/api/public/admin/run-scanner-self-test'
    | '/api/public/admin/sync-arlington'
    | '/api/public/admin/sync-bellevue'
    | '/api/public/admin/sync-la'
    | '/api/public/cron/health-check'
    | '/api/public/cron/sync-la-occupancy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/onboard'
    | '/profile'
    | '/saved'
    | '/scan'
    | '/session'
    | '/settings'
    | '/splash'
    | '/subscription'
    | '/admin/accuracy'
    | '/admin/analytics'
    | '/admin/arlington-coverage'
    | '/admin/bellevue-coverage'
    | '/admin/beta-readiness'
    | '/admin/forecast'
    | '/admin/health'
    | '/admin/la-coverage'
    | '/admin/provider-sync'
    | '/admin/reports'
    | '/admin/validation'
    | '/debug/parking'
    | '/admin/'
    | '/api/public/admin/arlington-self-test'
    | '/api/public/admin/run-scanner-self-test'
    | '/api/public/admin/sync-arlington'
    | '/api/public/admin/sync-bellevue'
    | '/api/public/admin/sync-la'
    | '/api/public/cron/health-check'
    | '/api/public/cron/sync-la-occupancy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ScanRoute: typeof ScanRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
  SubscriptionRoute: typeof SubscriptionRoute
  DebugParkingRoute: typeof DebugParkingRoute
  ApiPublicAdminArlingtonSelfTestRoute: typeof ApiPublicAdminArlingtonSelfTestRoute
  ApiPublicAdminRunScannerSelfTestRoute: typeof ApiPublicAdminRunScannerSelfTestRoute
  ApiPublicAdminSyncArlingtonRoute: typeof ApiPublicAdminSyncArlingtonRoute
  ApiPublicAdminSyncBellevueRoute: typeof ApiPublicAdminSyncBellevueRoute
  ApiPublicAdminSyncLaRoute: typeof ApiPublicAdminSyncLaRoute
  ApiPublicCronHealthCheckRoute: typeof ApiPublicCronHealthCheckRoute
  ApiPublicCronSyncLaOccupancyRoute: typeof ApiPublicCronSyncLaOccupancyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/debug/parking': {
      id: '/debug/parking'
      path: '/debug/parking'
      fullPath: '/debug/parking'
      preLoaderRoute: typeof DebugParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/validation': {
      id: '/admin/validation'
      path: '/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AdminValidationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provider-sync': {
      id: '/admin/provider-sync'
      path: '/provider-sync'
      fullPath: '/admin/provider-sync'
      preLoaderRoute: typeof AdminProviderSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/la-coverage': {
      id: '/admin/la-coverage'
      path: '/la-coverage'
      fullPath: '/admin/la-coverage'
      preLoaderRoute: typeof AdminLaCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forecast': {
      id: '/admin/forecast'
      path: '/forecast'
      fullPath: '/admin/forecast'
      preLoaderRoute: typeof AdminForecastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beta-readiness': {
      id: '/admin/beta-readiness'
      path: '/beta-readiness'
      fullPath: '/admin/beta-readiness'
      preLoaderRoute: typeof AdminBetaReadinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bellevue-coverage': {
      id: '/admin/bellevue-coverage'
      path: '/bellevue-coverage'
      fullPath: '/admin/bellevue-coverage'
      preLoaderRoute: typeof AdminBellevueCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arlington-coverage': {
      id: '/admin/arlington-coverage'
      path: '/arlington-coverage'
      fullPath: '/admin/arlington-coverage'
      preLoaderRoute: typeof AdminArlingtonCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accuracy': {
      id: '/admin/accuracy'
      path: '/accuracy'
      fullPath: '/admin/accuracy'
      preLoaderRoute: typeof AdminAccuracyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/sync-la-occupancy': {
      id: '/api/public/cron/sync-la-occupancy'
      path: '/api/public/cron/sync-la-occupancy'
      fullPath: '/api/public/cron/sync-la-occupancy'
      preLoaderRoute: typeof ApiPublicCronSyncLaOccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/health-check': {
      id: '/api/public/cron/health-check'
      path: '/api/public/cron/health-check'
      fullPath: '/api/public/cron/health-check'
      preLoaderRoute: typeof ApiPublicCronHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-la': {
      id: '/api/public/admin/sync-la'
      path: '/api/public/admin/sync-la'
      fullPath: '/api/public/admin/sync-la'
      preLoaderRoute: typeof ApiPublicAdminSyncLaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-bellevue': {
      id: '/api/public/admin/sync-bellevue'
      path: '/api/public/admin/sync-bellevue'
      fullPath: '/api/public/admin/sync-bellevue'
      preLoaderRoute: typeof ApiPublicAdminSyncBellevueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-arlington': {
      id: '/api/public/admin/sync-arlington'
      path: '/api/public/admin/sync-arlington'
      fullPath: '/api/public/admin/sync-arlington'
      preLoaderRoute: typeof ApiPublicAdminSyncArlingtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/run-scanner-self-test': {
      id: '/api/public/admin/run-scanner-self-test'
      path: '/api/public/admin/run-scanner-self-test'
      fullPath: '/api/public/admin/run-scanner-self-test'
      preLoaderRoute: typeof ApiPublicAdminRunScannerSelfTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/arlington-self-test': {
      id: '/api/public/admin/arlington-self-test'
      path: '/api/public/admin/arlington-self-test'
      fullPath: '/api/public/admin/arlington-self-test'
      preLoaderRoute: typeof ApiPublicAdminArlingtonSelfTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccuracyRoute: typeof AdminAccuracyRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArlingtonCoverageRoute: typeof AdminArlingtonCoverageRoute
  AdminBellevueCoverageRoute: typeof AdminBellevueCoverageRoute
  AdminBetaReadinessRoute: typeof AdminBetaReadinessRoute
  AdminForecastRoute: typeof AdminForecastRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLaCoverageRoute: typeof AdminLaCoverageRoute
  AdminProviderSyncRoute: typeof AdminProviderSyncRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminValidationRoute: typeof AdminValidationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccuracyRoute: AdminAccuracyRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArlingtonCoverageRoute: AdminArlingtonCoverageRoute,
  AdminBellevueCoverageRoute: AdminBellevueCoverageRoute,
  AdminBetaReadinessRoute: AdminBetaReadinessRoute,
  AdminForecastRoute: AdminForecastRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminLaCoverageRoute: AdminLaCoverageRoute,
  AdminProviderSyncRoute: AdminProviderSyncRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminValidationRoute: AdminValidationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ScanRoute: ScanRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
  SubscriptionRoute: SubscriptionRoute,
  DebugParkingRoute: DebugParkingRoute,
  ApiPublicAdminArlingtonSelfTestRoute: ApiPublicAdminArlingtonSelfTestRoute,
  ApiPublicAdminRunScannerSelfTestRoute: ApiPublicAdminRunScannerSelfTestRoute,
  ApiPublicAdminSyncArlingtonRoute: ApiPublicAdminSyncArlingtonRoute,
  ApiPublicAdminSyncBellevueRoute: ApiPublicAdminSyncBellevueRoute,
  ApiPublicAdminSyncLaRoute: ApiPublicAdminSyncLaRoute,
  ApiPublicCronHealthCheckRoute: ApiPublicCronHealthCheckRoute,
  ApiPublicCronSyncLaOccupancyRoute: ApiPublicCronSyncLaOccupancyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
